In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#Loading Dataset 
df = pd.read_csv("../data/Global_Superstore_UTF8.csv")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 18.4 MB

In [5]:
df.shape

(51290, 24)

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='str')

In [7]:
#Removing Duplicates 
df.duplicated().sum()

print("Shape Before:", df.shape)

df = df.drop_duplicates()

print("Shape After:", df.shape)

Shape Before: (51290, 24)
Shape After: (51290, 24)

In [8]:
#Check Missing Values
df.isnull().sum().sort_values(ascending=False)

Postal Code       41296
Row ID                0
Region                0
Shipping Cost         0
Profit                0
Discount              0
Quantity              0
Sales                 0
Product Name          0
Sub-Category          0
Category              0
Product ID            0
Market                0
Order ID              0
Country               0
State                 0
City                  0
Segment               0
Customer Name         0
Customer ID           0
Ship Mode             0
Ship Date             0
Order Date            0
Order Priority        0
dtype: int64

In [9]:
df['Postal Code'] = (
    df['Postal Code']
    .fillna(0)
    .astype(int)
    .astype(str)
    .replace('0', 'Unknown')
)

In [10]:
#Check Missing Values
df.isnull().sum().sort_values(ascending=False)

Row ID            0
Order ID          0
Shipping Cost     0
Profit            0
Discount          0
Quantity          0
Sales             0
Product Name      0
Sub-Category      0
Category          0
Product ID        0
Region            0
Market            0
Postal Code       0
Country           0
State             0
City              0
Segment           0
Customer Name     0
Customer ID       0
Ship Mode         0
Ship Date         0
Order Date        0
Order Priority    0
dtype: int64

In [11]:
#Fixing Date Columns
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

/var/folders/_s/c6bqm9gx7qd_v11y8xzv788r0000gn/T/ipykernel_47858/1237026461.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Order Date'] = pd.to_datetime(df['Order Date'])
/var/folders/_s/c6bqm9gx7qd_v11y8xzv788r0000gn/T/ipykernel_47858/1237026461.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [12]:
#Checking Numeric Columns
df[['Sales', 'Profit', 'Quantity', 'Discount']].describe()

              Sales        Profit      Quantity      Discount
count  51290.000000  51290.000000  51290.000000  51290.000000
mean     246.490581     28.610982      3.476545      0.142908
std      487.565361    174.340972      2.278766      0.212280
min        0.444000  -6599.978000      1.000000      0.000000
25%       30.758625      0.000000      2.000000      0.000000
50%       85.053000      9.240000      3.000000      0.000000
75%      251.053200     36.810000      5.000000      0.200000
max    22638.480000   8399.976000     14.000000      0.850000

In [13]:
#Handling Incorrect Data Types
df.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Segment                      str
City                         str
State                        str
Country                      str
Postal Code                  str
Market                       str
Region                       str
Product ID                   str
Category                     str
Sub-Category                 str
Product Name                 str
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority               str
dtype: object

In [14]:
#Creating Useful Columns
df['Year'] = df['Order Date'].dt.year

df['Month'] = df['Order Date'].dt.month_name()

df['Quarter'] = df['Order Date'].dt.quarter

In [15]:
month_order = [
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November', 'December'
]

df['Month'] = pd.Categorical(
    df['Month'],
    categories=month_order,
    ordered=True
)

In [16]:
#Standardizing Text Columns
df.columns = df.columns.str.strip()

text_cols = ['Category', 'Region', 'Segment', 'Sub-Category', 'Customer Name']

for col in text_cols:
    df[col] = df[col].str.strip()

In [17]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("-", "_")

display(df.head())

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Year,Month,Quarter
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical,2012,July,3
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical,2013,February,1
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium,2013,October,4
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium,2013,January,1
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical,2013,November,4

In [18]:
#Checking Unique Values
df['Category'].unique()
df['Region'].unique()
df['Segment'].unique()

<ArrowStringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str

In [19]:
#Outlier Analysis
# df['Sales'].sort_values(ascending=False).head(10)

In [20]:
df.info()

df.head()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_ID          51290 non-null  int64
 1   Order_ID        51290 non-null  str
 2   Order_Date      51290 non-null  datetime64[us]
 3   Ship_Date       51290 non-null  datetime64[us]
 4   Ship_Mode       51290 non-null  str
 5   Customer_ID     51290 non-null  str
 6   Customer_Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Postal_Code     51290 non-null  str
 12  Market          51290 non-null  str
 13  Region          51290 non-null  str
 14  Product_ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub_Category    51290 non-null  str
 17  Product_Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping_Cost   51290 non-null  float64
 23  Order_Priority  51290 non-null  str
 24  Year            51290 non-null  int32
 25  Month           51290 non-null  category
 26  Quarter         51290 non-null  int32
dtypes: category(1), datetime64[us](2), float64(4), int32(2), int64(2), str(16)
memory usage: 18.3 MB

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,State,...,Product_Name,Sales,Quantity,Discount,Profit,Shipping_Cost,Order_Priority,Year,Month,Quarter
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical,2012,July,3
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical,2013,February,1
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium,2013,October,4
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium,2013,January,1
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical,2013,November,4

In [21]:
df.isnull().sum()

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
City              0
State             0
Country           0
Postal_Code       0
Market            0
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping_Cost     0
Order_Priority    0
Year              0
Month             0
Quarter           0
dtype: int64

In [22]:
#Saving the Cleaned Dataset
df.to_csv("../data/cleaned_superstore.csv", index=False)